In [1]:
%reset -fs
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import pandas_profiling as pp
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

In [2]:
bet_df = pd.read_csv('betting_data.csv', index_col=0);bet_df

,Date,Name,Team,Position,Opp,Home/Away,Line,Moneyline,Projection,Diff,Pick,Result,over_under,seven_day_accuracy,successful_pick
0,2021-10-21,Bogdan,ATL,G,DAL,vs.,15.5,-115,16.57,1.07,15.5,11.0,o,0.47,0
1,2021-10-23,Bogdan,ATL,G,CLE,@,14.5,-115,15.29,0.79,14.5,5.0,o,0.45,0
2,2021-10-25,Bogdan,ATL,G,DET,vs.,15.5,-115,12.85,-2.65,15.5,14.0,u,0.45,1
3,2021-10-27,Bogdan,ATL,G,NOR,@,12.5,-125,13.70,1.20,12.5,12.0,o,0.45,0
4,2021-10-28,Bogdan,ATL,G,WAS,@,12.5,-105,16.72,4.22,12.5,14.0,o,0.42,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9386,2022-01-17,Ziaire Williams,MEM,G,CHI,vs.,8.5,-105,6.11,-2.39,8.5,2.0,u,0.58,1
9387,2022-01-19,Ziaire Williams,MEM,G,MIL,@,9.5,-103,8.70,-0.80,9.5,10.0,u,0.62,0
9388,2022-01-21,Ziaire Williams,MEM,G,DEN,@,9.5,100,8.90,-0.60,9.5,17.0,u,0.59,0
9389,2022-01-23,Ziaire Williams,MEM,G,DAL,@,10.5,-105,8.60,-1.90,10.5,9.0,u,0.55,1
9390,2022-01-26,Ziaire Williams,MEM,G,SAS,@,10.5,-132,8.20,-2.30,10.5,NaN,u,0.43,0

In [3]:
bet_df.Date = pd.to_datetime(bet_df.Date, infer_datetime_format=True)

In [4]:
stat_df = pd.read_csv('stathead_data.csv', index_col=0); stat_df

,Player,Age,Pos,Tm,Unnamed: 5,Opp,Unnamed: 7,Date,GS,MP,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,BPM
Rk,,,,,,,,,,,,,,,,,,,,,
1,LaMarcus Aldridge\aldrila01,36-092,F-C,BRK,@,MIL,L,2021-10-19,0,16,...,3,3,1,0,1,1,2,1,-1.1,-15.2
2,Grayson Allen\allengr01,26-011,G,MIL,NaN,BRK,W,2021-10-19,1,28,...,4,4,6,2,0,0,0,10,11.6,6.4
3,Giannis Antetokounmpo\antetgi01,26-317,F-G,MIL,NaN,BRK,W,2021-10-19,1,31,...,9,14,7,1,2,4,4,32,26.4,11.4
4,Thanasis Antetokounmpo\antetth01,29-093,F,MIL,NaN,BRK,W,2021-10-19,0,12,...,3,4,1,0,1,0,1,6,7.3,8.0
5,Carmelo Anthony\anthoca01,37-143,F,LAL,NaN,GSW,L,2021-10-19,0,26,...,4,4,2,0,0,1,2,9,4.3,-3.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15495,Robert Woodard II\woodaro01,22-126,F,SAC,@,ATL,L,2022-01-26,0,4,...,1,2,0,0,0,0,0,0,0.3,-11.9
15496,Delon Wright\wrighde01,29-275,G,ATL,NaN,SAC,W,2022-01-26,0,28,...,2,2,1,1,0,0,1,6,5.6,-4.5
15497,Trae Young\youngtr01,23-129,G,ATL,NaN,SAC,W,2022-01-26,1,25,...,2,3,10,4,0,4,0,17,15.5,7.7
15498,Omer Yurtseven\yurtsom01,23-221,C,MIA,NaN,NYK,W,2022-01-26,0,2,...,0,0,0,0,0,0,1,2,1.3,3.5
15499,Ivica Zubac\zubaciv01,24-314,C,LAC,@,ORL,W,2022-01-26,1,22,...,6,7,2,1,0,3,5,8,3.5,-8.7

In [5]:
stat_df.rename(columns={'Unnamed: 5': 'Home/Away', 'Unnamed: 7':'Game Result'}, inplace=True)

In [6]:
stat_df['Home/Away'] = stat_df['Home/Away'].fillna('Home')
stat_df['Home/Away'] = stat_df['Home/Away'].replace('@','Away')

In [7]:
stat_df.Date = pd.to_datetime(stat_df.Date, infer_datetime_format=True)

In [8]:
players = stat_df.Player.str.split('\\', expand=True)

In [9]:
stat_df.Player = players[0]

In [10]:
stat_df = stat_df.sort_values(by=['Player', 'Date'], axis=0)

In [11]:
stat_df

,Player,Age,Pos,Tm,Home/Away,Opp,Game Result,Date,GS,MP,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,BPM
Rk,,,,,,,,,,,,,,,,,,,,,
124,Aaron Gordon,26-034,F,DEN,Away,PHO,W,2021-10-20,1,29,...,6,8,4,0,1,3,2,12,12.3,6.1
435,Aaron Gordon,26-036,F,DEN,Home,SAS,W,2021-10-22,1,30,...,3,5,1,0,0,3,5,8,3.0,-8.1
959,Aaron Gordon,26-039,F,DEN,Home,CLE,L,2021-10-25,1,28,...,6,9,1,0,0,3,2,12,4.6,-6.5
1137,Aaron Gordon,26-040,F,DEN,Away,UTA,L,2021-10-26,1,34,...,6,7,1,1,1,4,5,20,12.6,-3.2
1611,Aaron Gordon,26-043,F,DEN,Home,DAL,W,2021-10-29,1,24,...,4,5,2,1,1,2,1,13,11.3,8.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14416,Ziaire Williams,20-129,F,MEM,Away,MIL,L,2022-01-19,1,33,...,1,1,1,1,0,0,1,10,5.5,-6.3
14701,Ziaire Williams,20-131,F,MEM,Away,DEN,W,2022-01-21,1,31,...,4,5,0,2,1,0,4,17,16.4,8.1
14998,Ziaire Williams,20-133,F,MEM,Away,DAL,L,2022-01-23,1,23,...,0,1,1,0,0,0,5,9,0.9,-9.6
15492,Ziaire Williams,20-136,F,MEM,Away,SAS,W,2022-01-26,1,26,...,3,3,2,1,0,2,3,11,6.4,-4.7
13098,Zylan Cheatham,26-056,F,UTA,Home,CLE,L,2022-01-12,0,5,...,0,0,0,0,0,0,0,0,-2.1,-30.2

In [12]:
team_stat_df = pd.read_csv('teamstats.csv', index_col=0)

In [13]:
team_stat_df.rename(columns={'Unnamed: 3': 'Home/Away'}, inplace=True)
team_stat_df['Home/Away'] = team_stat_df['Home/Away'].fillna('Home')
team_stat_df['Home/Away'] = team_stat_df['Home/Away'].replace('@','Away')

In [14]:
team_stat_df['Date'] = pd.to_datetime(team_stat_df.Date, infer_datetime_format=True)

In [15]:
merged_df_1 = pd.merge(stat_df, team_stat_df,  how='left', left_on=['Date','Tm', 'Opp'], right_on = ['Date','Tm', 'Opp'])

In [16]:
merged_df_1.to_csv('player_team_stats_merged.csv')

In [17]:
merged_df_1.Player.unique()

array(['Aaron Gordon', 'Aaron Henry', 'Aaron Holiday', 'Aaron Nesmith',
       'Aaron Wiggins', 'Abdel Nader', 'Ade Murkey', 'Admiral Schofield',
       'Ahmad Caver', 'Al Horford', 'Alec Burks', 'Aleem Ford',
       'Aleksej Pokusevski', 'Alex Caruso', 'Alex Len',
       'Alfonzo McKinnie', 'Alize Johnson', 'Alperen Şengün',
       'Amir Coffey', 'Andre Drummond', 'Andre Iguodala',
       'Andrew Wiggins', 'Anfernee Simons', 'Anthony Davis',
       'Anthony Edwards', 'Anthony Gill', 'Anthony Lamb', 'Armoni Brooks',
       'Arnoldas Kulboka', 'Austin Reaves', 'Austin Rivers',
       'Avery Bradley', 'Ayo Dosunmu', 'B.J. Johnson', 'Bam Adebayo',
       'Ben McLemore', 'Bismack Biyombo', 'Blake Griffin',
       'Boban Marjanović', 'Bobby Portis', 'Bogdan Bogdanović',
       'Bojan Bogdanović', 'Bol Bol', 'Bones Hyland', 'Brad Wanamaker',
       'Bradley Beal', 'Brandon Boston Jr.', 'Brandon Clarke',
       'Brandon Goodwin', 'Brandon Ingram', 'Brandon Knight',
       'Brandon Williams', 'Braxton Key', 'Brodric Thomas', 'Brook Lopez',
       'Bruce Brown', 'Bruno Fernando', 'Bryn Forbes', 'Buddy Hield',
       'C.J. Miles', 'CJ Elleby', 'CJ McCollum', 'Cade Cunningham',
       'Caleb Martin', 'Cam Reddish', 'Cam Thomas', 'Cameron Johnson',
       'Cameron McGriff', 'Cameron Oliver', 'Cameron Payne',
       'Caris LeVert', 'Carlik Jones', 'Carmelo Anthony',
       'Cassius Stanley', 'Cassius Winston', 'Cat Barber', 'Cedi Osman',
       'Chandler Hutchison', 'Charles Bassey', 'Charlie Brown Jr.',
       'Chaundee Brown Jr.', 'Cheick Diallo', 'Chimezie Metu',
       'Chris Boucher', 'Chris Chiozza', 'Chris Duarte', 'Chris Paul',
       'Chris Silva', 'Christian Wood', 'Chuma Okeke', 'Clint Capela',
       'Coby White', 'Cody Martin', 'Cody Zeller', 'Cole Anthony',
       'Collin Sexton', 'Corey Kispert', 'Cory Joseph', 'Craig Sword',
       "D'Angelo Russell", 'D.J. Augustin', 'D.J. Wilson',
       'DaQuan Jeffries', 'Daishen Nix', 'Dakota Mathias',
       'Dalano Banton', 'Damian Jones', 'Damian Lillard', 'Damion Lee',
       'Damyean Dotson', 'Daniel Gafford', 'Daniel Oturu', 'Daniel Theis',
       'Danilo Gallinari', 'Danny Green', 'Danuel House Jr.',
       'Darius Bazley', 'Darius Garland', 'Darren Collison',
       'David Duke Jr.', 'David Johnson', 'David Nwaba',
       'Davion Mitchell', 'Davon Reed', "Day'Ron Sharpe", "De'Aaron Fox",
       "De'Andre Hunter", "De'Anthony Melton", 'DeAndre Jordan',
       "DeAndre' Bembry", 'DeJon Jarreau', 'DeMar DeRozan',
       'DeMarcus Cousins', 'Dean Wade', 'Deandre Ayton',
       'Deividas Sirvydis', 'Dejounte Murray', 'Delon Wright',
       'Deni Avdija', 'Dennis Schröder', 'Dennis Smith Jr.',
       'Denzel Valentine', 'Derrick Favors', 'Derrick Jones Jr.',
       'Derrick Rose', 'Derrick Walton', 'Derrick White', 'Desmond Bane',
       'Devin Booker', 'Devin Vassell', 'Devon Dotson', 'Devontae Cacok',
       "Devonte' Graham", 'Dewayne Dedmon', 'Didi Louzada',
       'Dillon Brooks', 'Domantas Sabonis', 'Donovan Mitchell',
       'Donte DiVincenzo', 'Dorian Finney-Smith', 'Doug McDermott',
       'Draymond Green', 'Drew Eubanks', 'Duane Washington Jr.',
       'Duncan Robinson', 'Dwight Howard', 'Dwight Powell',
       'Dylan Windler', 'Dāvis Bertāns', 'Ed Davis', 'Elfrid Payton',
       'Elijah Hughes', 'Emanuel Terry', 'Emmanuel Mudiay',
       'Enes Freedom', 'Eric Bledsoe', 'Eric Gordon', 'Eric Paschall',
       'Eugene Omoruyi', 'Evan Fournier', 'Evan Mobley',
       'Facundo Campazzo', 'Frank Jackson', 'Frank Kaminsky',
       'Frank Ntilikina', 'Franz Wagner', 'Fred VanVleet',
       'Freddie Gillespie', 'Furkan Korkmaz', 'Gabe Vincent',
       'Gabriel Deck', 'Garrett Temple', 'Garrison Mathews', 'Gary Clark',
       'Gary Harris', 'Gary Payton II', 'Gary Trent Jr.', 'George Hill',
       'George King', 'Georges Niang', 'Georgios Kalaitzakis',
       'Giannis Antetokounmpo', 'Goga Bitadze', 'Goran Dragić',
       'Gordon Hayward', 'Gorgui Dieng', 'Grant Williams',
       'Grayson Allen', 'Greg Brown III', 'Greg Monroe', 'Hamidou Diallo',
       'Harrison Barnes', 'Hassan Whiteside', 'Hassani Gravett',
       'Haywood Highsmith', 'Herbert Jones', 'Ignas Brazdeikis',
       'Immanuel Quickley', 'Isaac Bonga', 'Isaac Okoro',
       'Isaiah Hartenstein', 'Isaiah Jackson', 'Isaiah Joe',
       'Isaiah Livers', 'Isaiah Roby', 'Isaiah Stewart', 'Isaiah Thomas',
       'Isaiah Todd', 'Ish Smith', 'Ish Wainright', 'Ivica Zubac',
       'JT Thor', 'Ja Morant', 'JaMychal Green', 'JaQuori McLaughlin',
       'JaVale McGee', 'Jabari Parker', 'Jaden McDaniels',
       'Jaden Springer', 'Jae Crowder', "Jae'Sean Tate",
       "Jahmi'us Ramsey", 'Jaime Echenique', 'Jake Layman',
       'Jakob Poeltl', 'Jalen Brunson', 'Jalen Green', 'Jalen Johnson',
       'Jalen McDaniels', 'Jalen Smith', 'Jalen Suggs', 'James Bouknight',
       'James Ennis III', 'James Harden', 'James Johnson',
       'Jamorko Pickett', 'Jared Butler', 'Jared Harper',
       'Jaren Jackson Jr.', 'Jarred Vanderbilt', 'Jarrett Allen',
       'Jarrett Culver', 'Jarron Cumberland', 'Javin DeLaurier',
       'Javonte Green', 'Javonte Smart', 'Jaxson Hayes', 'Jay Huff',
       'Jay Scrubb', 'Jaylen Brown', 'Jaylen Hoard', 'Jaylen Morris',
       'Jaylen Nowell', 'Jaysean Paige', 'Jayson Tatum', 'Jeff Dowtin',
       'Jeff Green', 'Jemerrio Jones', 'Jerami Grant',
       'Jeremiah Robinson-Earl', 'Jeremy Lamb', 'Jericho Sims',
       'Jevon Carter', 'Jimmy Butler', 'Jock Landale', 'Joe Harris',
       'Joe Ingles', 'Joe Johnson', 'Joe Wieskamp', 'Joel Ayayi',
       'Joel Embiid', 'John Collins', 'John Konchar', 'Jon Teske',
       'Jonas Valančiūnas', 'Jonathan Kuminga', 'Jordan Bell',
       'Jordan Clarkson', 'Jordan Goodwin', 'Jordan McLaughlin',
       'Jordan Nwora', 'Jordan Poole', 'Jordan Schakel', 'Jose Alvarado',
       'Josh Christopher', 'Josh Giddey', 'Josh Green', 'Josh Hart',
       'Josh Jackson', 'Josh Okogie', 'Josh Richardson', 'Joshua Primo',
       'Jrue Holiday', 'Juan Toscano-Anderson', 'Juancho Hernangómez',
       'Julius Randle', 'Justin Anderson', 'Justin Champagnie',
       'Justin Holiday', 'Justin Jackson', 'Justin Robinson',
       'Justise Winslow', 'Jusuf Nurkić', 'Juwan Morgan', 'KZ Okpala',
       'Kai Jones', 'Karl-Anthony Towns', 'Keifer Sykes',
       'Keita Bates-Diop', 'Kelan Martin', 'Keldon Johnson',
       'Keljin Blevins', 'Kelly Olynyk', 'Kelly Oubre Jr.',
       'Kemba Walker', 'Kenrich Williams', 'Kent Bazemore',
       'Kentavious Caldwell-Pope', 'Kenyon Martin Jr.', 'Keon Johnson',
       'Kessler Edwards', 'Kevin Durant', 'Kevin Huerter', 'Kevin Knox',
       'Kevin Love', 'Kevin Pangos', 'Kevin Porter Jr.', 'Kevon Looney',
       'Khem Birch', 'Khris Middleton', 'Killian Hayes', 'Killian Tillie',
       'Kira Lewis Jr.', 'Klay Thompson', 'Kristaps Porziņģis',
       'Kyle Anderson', 'Kyle Guy', 'Kyle Kuzma', 'Kyle Lowry',
       'Kyrie Irving', 'LaMarcus Aldridge', 'LaMelo Ball',
       'Lamar Stevens', 'Lance Stephenson', 'Landry Shamet',
       'Langston Galloway', 'Larry Nance Jr.', 'Lauri Markkanen',
       'LeBron James', 'Leandro Bolmaro', 'Lindell Wigginton',
       'Lonnie Walker IV', 'Lonzo Ball', 'Lou Williams', 'Louis King',
       'Luguentz Dort', 'Luka Dončić', 'Luka Garza', 'Luke Kennard',
       'Luke Kornet', 'M.J. Walker', 'Mac McClung', 'Malachi Flynn',
       'Malcolm Brogdon', 'Malcolm Hill', 'Malik Beasley', 'Malik Fitts',
       'Malik Monk', 'Malik Newman', 'Mamadi Diakite', 'Marcus Garrett',
       'Marcus Morris', 'Marcus Smart', 'Markieff Morris',
       'Marko Simonovic', 'Markus Howard', 'Marquese Chriss',
       'Marvin Bagley III', 'Mason Jones', 'Mason Plumlee',
       'Matisse Thybulle', 'Matt Mooney', 'Matt Thomas',
       'Maurice Harkless', 'Max Strus', 'Maxi Kleber',
       'McKinley Wright IV', 'Micah Potter', 'Michael Porter Jr.',
       'Mikal Bridges', 'Mike Conley', 'Mike Muscala', 'Miles Bridges',
       'Miles McBride', 'Mitchell Robinson', 'Miye Oni', 'Mo Bamba',
       'Monte Morris', 'Montrezl Harrell', 'Moritz Wagner', 'Moses Brown',
       'Moses Moody', 'Moses Wright', 'Mychal Mulder', 'Myles Powell',
       'Myles Turner', 'Naji Marshall', 'Nassir Little', 'Nate Hinton',
       'Nathan Knight', 'Naz Reid', 'Neemias Queta', 'Nemanja Bjelica',
       'Nerlens Noel', 'Nic Claxton', 'Nick Richards',
       'Nickeil Alexander-Walker', 'Nicolas Batum', 'Nik Stauskas',
       'Nikola Jokić', 'Nikola Vučević', 'Norman Powell', 'Norvel Pelle',
       'OG Anunoby', 'Obi Toppin', 'Olivier Sarr', 'Omer Yurtseven',
       'Onyeka Okongwu', 'Oshae Brissett', 'Otto Porter Jr.',
       'P.J. Tucker', 'P.J. Washington', 'PJ Dozier', 'Paris Bass',
       'Pascal Siakam', 'Pat Connaughton', 'Patrick Beverley',
       'Patrick Williams', 'Patty Mills', 'Paul George', 'Paul Millsap',
       'Paul Reed', 'Paul Watson', 'Payton Pritchard', 'Petr Cornelie',
       'Precious Achiuwa', 'Quentin Grimes', 'Quinndary Weatherspoon',
       'R.J. Hampton', 'RJ Barrett', 'RJ Nembhard Jr.', 'Rajon Rondo',
       'Raul Neto', 'Rayjon Tucker', 'Reggie Bullock', 'Reggie Jackson',
       'Reggie Perry', 'Richaun Holmes', 'Ricky Rubio', 'Rob Edwards',
       'Robert Covington', 'Robert Williams', 'Robert Woodard II',
       'Robin Lopez', 'Rodney Hood', 'Rodney McGruder', 'Romeo Langford',
       "Royce O'Neale", 'Rudy Gay', 'Rudy Gobert', 'Rui Hachimura',
       'Russell Westbrook', 'Saben Lee', 'Saddiq Bey', 'Sam Dekker',
       'Sam Hauser', 'Sam Merrill', 'Sandro Mamukelashvili',
       'Santi Aldama', 'Scottie Barnes', 'Scottie Lewis', 'Scotty Hopson',
       'Sekou Doumbouya', 'Semi Ojeleye', 'Serge Ibaka', 'Seth Curry',
       'Shai Gilgeous-Alexander', 'Shake Milton', 'Shaq Buchanan',
       'Shaquille Harrison', 'Sharife Cooper', 'Skylar Mays',
       'Solomon Hill', 'Spencer Dinwiddie', 'Stanley Johnson',
       'Stephen Curry', 'Sterling Brown', 'Steven Adams',
       'Svi Mykhailiuk', 'T.J. McConnell', 'Tacko Fall', 'Taj Gibson',
       'Talen Horton-Tucker', 'Taurean Prince', 'Terance Mann',
       'Terence Davis', 'Terrence Ross', 'Terry Rozier', 'Terry Taylor',
       'Thaddeus Young', 'Thanasis Antetokounmpo', 'Theo Pinson',
       'Thomas Bryant', 'Théo Maledon', 'Tim Frazier', 'Tim Hardaway Jr.',
       'Timothé Luwawu-Cabarrot', 'Tobias Harris', 'Tomáš Satoranský',
       'Tony Bradley', 'Tony Snell', 'Torrey Craig', 'Trae Young',
       'Trayvon Palmer', 'Tre Jones', 'Tre Mann', 'Tre Scott',
       'Tremont Waters', 'Trendon Watford', 'Trent Forrest',
       'Trevelin Queen', 'Trevor Ariza', 'Trey Burke', 'Trey Lyles',
       'Trey Murphy III', 'Tristan Thompson', 'Troy Brown Jr.',
       'Ty Jerome', 'Tyler Cook', 'Tyler Hall', 'Tyler Herro',
       'Tyler Johnson', 'Tyrell Terry', 'Tyrese Haliburton',
       'Tyrese Maxey', 'Tyus Jones', 'Udoka Azubuike', 'Udonis Haslem',
       'Usman Garuba', 'Vernon Carey Jr.', 'Vit Krejci', 'Vlatko Čančar',
       'Wayne Ellington', 'Wayne Selden', 'Wendell Carter Jr.',
       'Wenyen Gabriel', 'Wes Iwundu', 'Wesley Matthews', 'Will Barton',
       'Willie Cauley-Stein', 'Willy Hernangómez', 'Xavier Moon',
       'Xavier Sneed', 'Xavier Tillman Sr.', 'Yuta Watanabe', 'Yves Pons',
       'Zach LaVine', 'Zeke Nnaji', 'Ziaire Williams', 'Zylan Cheatham'],
      dtype=object)

In [18]:
bet_df.dtypes

Date                  datetime64[ns]
Name                          object
Team                          object
Position                      object
Opp                           object
Home/Away                     object
Line                         float64
Moneyline                      int64
Projection                   float64
Diff                         float64
Pick                         float64
Result                       float64
over_under                    object
seven_day_accuracy           float64
successful_pick                int64
dtype: object

In [19]:
merged_df_1.dtypes

Player          object
Age             object
Pos             object
Tm              object
Home/Away_x     object
                ...
3P%.1          float64
FT.1             int64
FTA.1            int64
FT%.1          float64
PTS.1            int64
Length: 63, dtype: object

In [20]:
bet_df

,Date,Name,Team,Position,Opp,Home/Away,Line,Moneyline,Projection,Diff,Pick,Result,over_under,seven_day_accuracy,successful_pick
0,2021-10-21,Bogdan,ATL,G,DAL,vs.,15.5,-115,16.57,1.07,15.5,11.0,o,0.47,0
1,2021-10-23,Bogdan,ATL,G,CLE,@,14.5,-115,15.29,0.79,14.5,5.0,o,0.45,0
2,2021-10-25,Bogdan,ATL,G,DET,vs.,15.5,-115,12.85,-2.65,15.5,14.0,u,0.45,1
3,2021-10-27,Bogdan,ATL,G,NOR,@,12.5,-125,13.70,1.20,12.5,12.0,o,0.45,0
4,2021-10-28,Bogdan,ATL,G,WAS,@,12.5,-105,16.72,4.22,12.5,14.0,o,0.42,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9386,2022-01-17,Ziaire Williams,MEM,G,CHI,vs.,8.5,-105,6.11,-2.39,8.5,2.0,u,0.58,1
9387,2022-01-19,Ziaire Williams,MEM,G,MIL,@,9.5,-103,8.70,-0.80,9.5,10.0,u,0.62,0
9388,2022-01-21,Ziaire Williams,MEM,G,DEN,@,9.5,100,8.90,-0.60,9.5,17.0,u,0.59,0
9389,2022-01-23,Ziaire Williams,MEM,G,DAL,@,10.5,-105,8.60,-1.90,10.5,9.0,u,0.55,1
9390,2022-01-26,Ziaire Williams,MEM,G,SAS,@,10.5,-132,8.20,-2.30,10.5,NaN,u,0.43,0

In [21]:
mat1 = []
mat2 = []


list1 = bet_df['Name'].tolist()
list2 = merged_df_1['Player'].tolist()

threshold=75

for i in list1:
    mat1.append(process.extract(i, list2, limit=2))
bet_df['Matches'] = mat1
bet_df

,Date,Name,Team,Position,Opp,Home/Away,Line,Moneyline,Projection,Diff,Pick,Result,over_under,seven_day_accuracy,successful_pick,Matches
0,2021-10-21,Bogdan,ATL,G,DAL,vs.,15.5,-115,16.57,1.07,15.5,11.0,o,0.47,0,"[(Bogdan Bogdanović, 90), (Bogdan Bogdanović, ..."
1,2021-10-23,Bogdan,ATL,G,CLE,@,14.5,-115,15.29,0.79,14.5,5.0,o,0.45,0,"[(Bogdan Bogdanović, 90), (Bogdan Bogdanović, ..."
2,2021-10-25,Bogdan,ATL,G,DET,vs.,15.5,-115,12.85,-2.65,15.5,14.0,u,0.45,1,"[(Bogdan Bogdanović, 90), (Bogdan Bogdanović, ..."
3,2021-10-27,Bogdan,ATL,G,NOR,@,12.5,-125,13.70,1.20,12.5,12.0,o,0.45,0,"[(Bogdan Bogdanović, 90), (Bogdan Bogdanović, ..."
4,2021-10-28,Bogdan,ATL,G,WAS,@,12.5,-105,16.72,4.22,12.5,14.0,o,0.42,1,"[(Bogdan Bogdanović, 90), (Bogdan Bogdanović, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9386,2022-01-17,Ziaire Williams,MEM,G,CHI,vs.,8.5,-105,6.11,-2.39,8.5,2.0,u,0.58,1,"[(Ziaire Williams, 100), (Ziaire Williams, 100)]"
9387,2022-01-19,Ziaire Williams,MEM,G,MIL,@,9.5,-103,8.70,-0.80,9.5,10.0,u,0.62,0,"[(Ziaire Williams, 100), (Ziaire Williams, 100)]"
9388,2022-01-21,Ziaire Williams,MEM,G,DEN,@,9.5,100,8.90,-0.60,9.5,17.0,u,0.59,0,"[(Ziaire Williams, 100), (Ziaire Williams, 100)]"
9389,2022-01-23,Ziaire Williams,MEM,G,DAL,@,10.5,-105,8.60,-1.90,10.5,9.0,u,0.55,1,"[(Ziaire Williams, 100), (Ziaire Williams, 100)]"
9390,2022-01-26,Ziaire Williams,MEM,G,SAS,@,10.5,-132,8.20,-2.30,10.5,NaN,u,0.43,0,"[(Ziaire Williams, 100), (Ziaire Williams, 100)]"

In [22]:
bet_df.to_csv('fuzzy_matches_bet_df.csv')